clean action file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,13 +8,13 @@ permissions:
 
 jobs:
 
-  print_context:
-    runs-on: ubuntu-latest
-    steps:
-      - env:
-          EVENT_CONTEXT: ${{ toJSON(github) }}
-        run: |
-          echo $EVENT_CONTEXT
+#   print_context:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - env:
+#           EVENT_CONTEXT: ${{ toJSON(github) }}
+#         run: |
+#           echo $EVENT_CONTEXT
           
   main-job:
     if: github.ref_name == 'main'
@@ -51,14 +51,7 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-        
-    #   - name: Read Index file content
-    #     id: read_index
-    #     run: |
-    #       INDEX_CONTENT=$(cat index.mjs)
-    #       echo "index_content<<EOF" >> $GITHUB_OUTPUT
-    #       echo "$INDEX_CONTENT" >> $GITHUB_OUTPUT
-    #       echo "EOF" >> $GITHUB_OUTPUT
+
       - name: Zip code
         run: |
            zip -r deployment.zip . -x ".git/*" ".github/*" "*.zip"
@@ -69,23 +62,19 @@ jobs:
             commit_message: "Add deployment.zip"
             file_pattern: deployment.zip
 
-    #   - name: Send File contents to endpoint as JSON    
-    #   # - name: Zip code
-    #     run: |
-    #       zip -r deployment.zip . -x ".git/*" ".github/*"
-    #   - name: Deploy to endpoint
-    #     run: |
-    #       curl -X POST \
-    #         --data-binary "@deployment.zip" \
-    #         -H "Content-Type: application/octet-stream" \
-    #         -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
-    #         -H "Branch: ${{ github.ref_name }}" \
-    #         -H "Repository: ${{ github.repository }}" \
-    #         https://jsf58ekjw3.execute-api.us-west-2.amazonaws.com/prod/deploy
-    #       if [ $? -ne 0 ]; then
-    #         echo "Deployment failed!"
-    #         exit 1
-    #       fi
+      - name: Deploy to endpoint
+        run: |
+          curl -X POST \
+            --data-binary "@deployment.zip" \
+            -H "Content-Type: application/octet-stream" \
+            -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
+            -H "Branch: ${{ github.ref_name }}" \
+            -H "Repository: ${{ github.repository }}" \
+            https://jsf58ekjw3.execute-api.us-west-2.amazonaws.com/prod/deploy
+          if [ $? -ne 0 ]; then
+            echo "Deployment failed!"
+            exit 1
+          fi
 
   common-job:
     runs-on: ubuntu-latest
